name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: List submodules
      run: git submodule status     

    - name: Install cmake
      run: sudo apt-get update && sudo apt-get -y install cmake meson

    # VCPKG Bootstrap
    - name: bootstrap vcpkg
      run: make bootstrap

    # Run the cmake setup for a Natve build
    - name: CMake setup
      run: |
        make configureDebug
        steps.continue_on_error

    - name: Show vcpkg log
      run: cat /home/runner/work/clevisLib/clevisLib/build/vcpkg-manifest-install.log

    # Build it!
    - name: Build
      run: make build

